import { readFileSync, existsSync, readdirSync } from 'fs'
import { execSync } from 'child_process'
import { join, basename } from 'path'
import bundledRegistry from '@/lib/agents.json'
import type { Agent } from '@/lib/types'

/** Raw agent data from JSON (everything except runtime-loaded soul and crons) */
export type AgentEntry = Omit<Agent, 'soul' | 'crons'>

/** Color palette assigned to auto-discovered agents */
const DISCOVER_COLORS = [
  '#f5c518', '#a855f7', '#3b82f6', '#22c55e', '#f97316',
  '#eab308', '#14b8a6', '#60a5fa', '#f59e0b', '#94a3b8',
  '#06b6d4', '#ec4899', '#84cc16', '#8b5cf6', '#ef4444',
]

// ---------------------------------------------------------------------------
// Heading / identity extraction helpers (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Parse a SOUL.md heading into a clean agent name and optional title.
 *
 * Handles all observed heading formats:
 *   "# SOUL.md — VERA"                 → name "VERA"
 *   "# SOUL.md — KAZE, Flight Research Agent" → name "KAZE", title "Flight Research Agent"
 *   "# ECHO — Community Voice Monitor" → name "ECHO", title "Community Voice Monitor"
 *   "# SOUL.md - Who You Are"          → name null (not a useful agent name)
 *   "# QUILL — Herald's Content Writer" → name "QUILL", title "Herald's Content Writer"
 */
export function parseSoulHeading(content: string): { name: string | null; title: string | null } {
  const match = content.match(/^#\s+(.+)/m)
  if (!match) return { name: null, title: null }

  let heading = match[1].trim()

  // Strip "SOUL.md — ", "SOUL.md - ", "SOUL.md:" prefixes
  heading = heading.replace(/^SOUL\.md\s*[—–\-:]\s*/i, '')

  // If the heading is generic (e.g. "Who You Are"), it's not a useful agent name
  if (/^who\s+you\s+are/i.test(heading)) return { name: null, title: null }

  // Split on em-dash / en-dash to separate name from description
  const dashParts = heading.split(/\s*[—–]\s*/)
  const nameAndMaybeTitle = dashParts[0].trim()
  const descAfterDash = dashParts.length > 1 ? dashParts.slice(1).join(' — ').trim() : null

  // The name might contain a comma: "LUMEN, SEO Team Director"
  const commaParts = nameAndMaybeTitle.split(/,\s*/)
  const name = commaParts[0].trim() || null
  const titleFromComma = commaParts.length > 1 ? commaParts.slice(1).join(', ').trim() : null

  const title = titleFromComma || descAfterDash || null
  return { name, title }
}

/**
 * Parse an IDENTITY.md file for agent name and emoji.
 *
 * Expected format (generated by OpenClaw bootstrap):
 *   - **Name:** Jarvis
 *   - **Emoji:** 🤖
 */
export function parseIdentity(content: string): { name: string | null; emoji: string | null } {
  const nameMatch = content.match(/\*\*Name:\*\*\s*(.+)/i)
  const emojiMatch = content.match(/\*\*Emoji:\*\*\s*(\S+)/i)
  return {
    name: nameMatch ? nameMatch[1].trim() : null,
    emoji: emojiMatch ? emojiMatch[1].trim() : null,
  }
}

/**
 * Convert a directory slug to a display name: "my-agent" -> "My Agent"
 */
function slugToName(slug: string): string {
  return slug
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

/**
 * Read a file and return its content, or null on any error.
 */
function safeRead(filePath: string): string | null {
  try {
    if (!existsSync(filePath)) return null
    return readFileSync(filePath, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Scan a directory for sub-agent .md files (e.g. sub-agents/QUILL.md, members/WRITER.md).
 * Returns an array of { fileName, content } for each .md file found.
 */
function scanSubAgentDir(dirPath: string): { fileName: string; content: string }[] {
  if (!existsSync(dirPath)) return []
  try {
    return readdirSync(dirPath)
      .filter(f => f.endsWith('.md'))
      .map(f => {
        const content = safeRead(join(dirPath, f))
        return content ? { fileName: f, content } : null
      })
      .filter((x): x is { fileName: string; content: string } => x !== null)
  } catch {
    return []
  }
}

/**
 * Scan a parent agent directory for child subdirectories containing SOUL.md.
 * Skips sub-agents/ and members/ (already handled by scanSubAgentDir).
 */
function scanSubdirAgents(parentDir: string): { dirName: string; content: string }[] {
  if (!existsSync(parentDir)) return []
  try {
    return readdirSync(parentDir, { withFileTypes: true })
      .filter(e => e.isDirectory() && e.name !== 'sub-agents' && e.name !== 'members')
      .map(e => {
        const content = safeRead(join(parentDir, e.name, 'SOUL.md'))
        return content ? { dirName: e.name, content } : null
      })
      .filter((x): x is { dirName: string; content: string } => x !== null)
  } catch {
    return []
  }
}

// ---------------------------------------------------------------------------
// Auto-discovery
// ---------------------------------------------------------------------------

/**
 * Auto-discover agents from $WORKSPACE_PATH.
 *
 * Scans the workspace for:
 *   - IDENTITY.md at root (for root agent name/emoji)
 *   - SOUL.md at root (root orchestrator)
 *   - agents/<dir>/SOUL.md (top-level agents)
 *   - agents/<dir>/sub-agents/*.md (nested sub-agents)
 *   - agents/<dir>/members/*.md (team member agents)
 *
 * Returns null if nothing can be discovered.
 */
function discoverAgents(workspacePath: string): AgentEntry[] | null {
  const agentsDir = join(workspacePath, 'agents')
  const rootSoulPath = join(workspacePath, 'SOUL.md')
  const identityPath = join(workspacePath, 'IDENTITY.md')
  const hasRoot = existsSync(rootSoulPath)

  // Scan agents/ directory for all subdirectories (even without SOUL.md, may have sub-agents)
  let allAgentDirs: string[] = []
  if (existsSync(agentsDir)) {
    try {
      const entries = readdirSync(agentsDir, { withFileTypes: true })
      allAgentDirs = entries.filter(e => e.isDirectory()).map(e => e.name)
    } catch {}
  }

  // Need at least a root or agent directories to discover
  if (!hasRoot && allAgentDirs.length === 0) return null

  const discovered: AgentEntry[] = []
  let colorIndex = 0
  const directReportIds: string[] = []

  // --- Root agent ---
  let rootId = 'main'
  let rootName = 'Main'
  let rootEmoji = '\u{1F916}'

  if (hasRoot) {
    // Try IDENTITY.md first (most reliable source for name/emoji)
    const identityContent = safeRead(identityPath)
    if (identityContent) {
      const identity = parseIdentity(identityContent)
      if (identity.name) {
        rootName = identity.name
        rootId = identity.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
      }
      if (identity.emoji) rootEmoji = identity.emoji
    }

    // Fall back to SOUL.md heading if IDENTITY.md didn't provide a name
    if (rootName === 'Main') {
      const soulContent = safeRead(rootSoulPath)
      if (soulContent) {
        const parsed = parseSoulHeading(soulContent)
        if (parsed.name) {
          rootName = parsed.name
          rootId = parsed.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
        }
      }
    }

    discovered.push({
      id: rootId,
      name: rootName,
      title: 'Orchestrator',
      reportsTo: null,
      directReports: directReportIds, // populated below
      soulPath: 'SOUL.md',
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: rootEmoji,
      tools: ['read', 'write', 'exec', 'message'],
      memoryPath: null,
      description: 'Top-level orchestrator.',
    })

    // We'll fill directReportIds as we discover agents below
    for (const dirName of allAgentDirs) {
      if (dirName === rootId) continue // root-matching dir scanned in main loop
      const hasSoul = existsSync(join(agentsDir, dirName, 'SOUL.md'))
      const hasSubAgents = existsSync(join(agentsDir, dirName, 'sub-agents'))
      const hasMembers = existsSync(join(agentsDir, dirName, 'members'))
      if (hasSoul || hasSubAgents || hasMembers) {
        directReportIds.push(dirName)
      }
    }
  }

  // --- Top-level agents ---
  for (const dirName of allAgentDirs) {
    // Root-matching directory: scan for sub-agents but don't create a duplicate root entry
    if (hasRoot && dirName === rootId) {
      const rootAgentDir = join(agentsDir, dirName)
      const rootSubFiles = [
        ...scanSubAgentDir(join(rootAgentDir, 'sub-agents')),
        ...scanSubAgentDir(join(rootAgentDir, 'members')),
      ]
      const rootSubIds = new Set<string>()
      for (const sub of rootSubFiles) {
        const subId = `${rootId}-${basename(sub.fileName, '.md').toLowerCase()}`
        rootSubIds.add(subId)
        directReportIds.push(subId)
        const subParsed = parseSoulHeading(sub.content)
        const subName = subParsed.name || slugToName(basename(sub.fileName, '.md'))
        const subTitle = subParsed.title || 'Agent'
        discovered.push({
          id: subId,
          name: subName,
          title: subTitle,
          reportsTo: rootId,
          directReports: [],
          soulPath: null,
          voiceId: null,
          color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
          emoji: subName.charAt(0).toUpperCase(),
          tools: ['read', 'write'],
          memoryPath: null,
          description: `${subName} agent.`,
        })
      }

      for (const sub of scanSubdirAgents(rootAgentDir)) {
        const subId = `${rootId}-${sub.dirName}`
        if (rootSubIds.has(subId)) continue
        directReportIds.push(subId)
        const subParsed = parseSoulHeading(sub.content)
        const subName = subParsed.name || slugToName(sub.dirName)
        const subTitle = subParsed.title || 'Agent'
        discovered.push({
          id: subId,
          name: subName,
          title: subTitle,
          reportsTo: rootId,
          directReports: [],
          soulPath: `agents/${rootId}/${sub.dirName}/SOUL.md`,
          voiceId: null,
          color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
          emoji: subName.charAt(0).toUpperCase(),
          tools: ['read', 'write'],
          memoryPath: null,
          description: `${subName} agent.`,
        })
      }
      continue
    }

    const soulFile = join(agentsDir, dirName, 'SOUL.md')
    const hasSoul = existsSync(soulFile)
    const subAgentsDir = join(agentsDir, dirName, 'sub-agents')
    const membersDir = join(agentsDir, dirName, 'members')
    const hasSubAgents = existsSync(subAgentsDir)
    const hasMembers = existsSync(membersDir)

    // Skip directories with nothing useful
    if (!hasSoul && !hasSubAgents && !hasMembers) continue

    let name = slugToName(dirName)
    let title = 'Agent'
    const subAgentIds: string[] = []

    // Parse SOUL.md for name and title
    if (hasSoul) {
      const content = safeRead(soulFile)
      if (content) {
        const parsed = parseSoulHeading(content)
        if (parsed.name) name = parsed.name
        if (parsed.title) title = parsed.title

        // Also check for Role: or Title: lines as fallback
        if (title === 'Agent') {
          const roleMatch = content.match(/^##\s*Role\b/mi)
          if (roleMatch) {
            // Try to get first line after ## Role
            const afterRole = content.slice(roleMatch.index! + roleMatch[0].length)
            const firstLine = afterRole.match(/\n\s*\n(.+)/)?.[1]?.trim()
            // Don't use long role descriptions as titles
            if (firstLine && firstLine.length < 80) title = firstLine
          }
        }
      }
    }

    // Discover sub-agents (sub-agents/ and members/ directories)
    const subAgentFiles = [
      ...scanSubAgentDir(subAgentsDir),
      ...scanSubAgentDir(membersDir),
    ]

    for (const sub of subAgentFiles) {
      const subId = `${dirName}-${basename(sub.fileName, '.md').toLowerCase()}`
      subAgentIds.push(subId)

      const subParsed = parseSoulHeading(sub.content)
      const subName = subParsed.name || slugToName(basename(sub.fileName, '.md'))
      const subTitle = subParsed.title || 'Agent'

      discovered.push({
        id: subId,
        name: subName,
        title: subTitle,
        reportsTo: dirName,
        directReports: [],
        soulPath: null, // sub-agents use non-standard paths, soul loaded differently
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: subName.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        memoryPath: null,
        description: `${subName} agent.`,
      })
    }

    // Discover subdirectory agents (child dirs with SOUL.md)
    const subdirAgents = scanSubdirAgents(join(agentsDir, dirName))
    const existingSubIds = new Set(subAgentIds)
    for (const sub of subdirAgents) {
      const subId = `${dirName}-${sub.dirName}`
      if (existingSubIds.has(subId)) continue
      subAgentIds.push(subId)
      const subParsed = parseSoulHeading(sub.content)
      const subName = subParsed.name || slugToName(sub.dirName)
      const subTitle = subParsed.title || 'Agent'
      discovered.push({
        id: subId,
        name: subName,
        title: subTitle,
        reportsTo: dirName,
        directReports: [],
        soulPath: `agents/${dirName}/${sub.dirName}/SOUL.md`,
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: subName.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        memoryPath: null,
        description: `${subName} agent.`,
      })
    }

    discovered.push({
      id: dirName,
      name,
      title,
      reportsTo: hasRoot ? rootId : null,
      directReports: subAgentIds,
      soulPath: hasSoul ? `agents/${dirName}/SOUL.md` : null,
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: name.charAt(0).toUpperCase(),
      tools: ['read', 'write'],
      memoryPath: null,
      description: `${name} agent.`,
    })
  }

  return discovered.length > 0 ? discovered : null
}

// ---------------------------------------------------------------------------
// CLI-based multi-workspace discovery (openclaw agents list)
// ---------------------------------------------------------------------------

/**
 * Raw entry from `openclaw agents list --json`.
 *
 * Real CLI output shape (verified against OpenClaw docs + live CLI):
 *   { id, identityName, identityEmoji, identitySource,
 *     workspace, agentDir, model, bindings, isDefault, routes }
 */
interface CliAgentEntry {
  id: string
  identityName?: string
  identityEmoji?: string
  workspace?: string
  isDefault?: boolean
}

/**
 * Call `openclaw agents list --json` and return parsed entries.
 * Returns null on any failure (CLI not found, bad JSON, timeout).
 */
export function listCliAgents(openclawBin: string): CliAgentEntry[] | null {
  try {
    const raw = execSync(`${openclawBin} agents list --json`, {
      encoding: 'utf-8',
      timeout: 10000,
    })
    const parsed = JSON.parse(raw)
    const agents: unknown[] = Array.isArray(parsed) ? parsed : []
    if (agents.length === 0) return null
    return agents as CliAgentEntry[]
  } catch {
    return null
  }
}

/**
 * Scan additional workspaces found via CLI that differ from the primary
 * WORKSPACE_PATH. For each extra workspace, run discoverAgents() and
 * merge results into the existing registry.
 *
 * Agents from other workspaces are independent (no cross-workspace hierarchy).
 * If the other workspace has a root orchestrator, it becomes a top-level peer
 * in the primary workspace's registry.
 */
function mergeExtraWorkspaces(
  existing: AgentEntry[],
  cliAgents: CliAgentEntry[],
  primaryWorkspace: string,
): AgentEntry[] {
  const existingIds = new Set(existing.map(a => a.id))
  const added: AgentEntry[] = []
  let colorIndex = existing.length

  for (const cli of cliAgents) {
    const ws = cli.workspace
    // Skip agents whose workspace matches the primary (already discovered)
    if (!ws || ws === primaryWorkspace) continue

    // Try discovering agents from this workspace's filesystem
    const discovered = discoverAgents(ws)
    if (discovered) {
      for (const agent of discovered) {
        if (existingIds.has(agent.id)) continue
        // Agents from other workspaces are top-level peers (no cross-workspace hierarchy)
        if (agent.reportsTo && !existingIds.has(agent.reportsTo)) {
          agent.reportsTo = null
        }
        added.push(agent)
        existingIds.add(agent.id)
      }
    } else {
      // Workspace has no agents/ dir — create a minimal entry from CLI identity
      const id = cli.id
      if (existingIds.has(id)) continue
      const name = cli.identityName || slugToName(id)
      added.push({
        id,
        name,
        title: 'Agent',
        reportsTo: null,
        directReports: [],
        soulPath: null,
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: cli.identityEmoji || name.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        memoryPath: null,
        description: `${name} agent.`,
      })
      existingIds.add(id)
    }
  }

  return [...existing, ...added]
}

/**
 * Load the agent registry.
 *
 * Resolution order:
 *   1. $WORKSPACE_PATH/clawport/agents.json  (user's own config)
 *   2. Auto-discovered from $WORKSPACE_PATH   (agents/ directory scan)
 *      + merged with other workspaces from `openclaw agents list --json`
 *   3. CLI-only discovery (scans each agent's workspace)
 *   4. Bundled lib/agents.json               (default example registry)
 */
export function loadRegistry(): AgentEntry[] {
  const workspacePath = process.env.WORKSPACE_PATH
  const openclawBin = process.env.OPENCLAW_BIN

  if (workspacePath) {
    // 1. User-provided override
    const userRegistryPath = join(workspacePath, 'clawport', 'agents.json')
    if (existsSync(userRegistryPath)) {
      try {
        const raw = readFileSync(userRegistryPath, 'utf-8')
        return JSON.parse(raw) as AgentEntry[]
      } catch {
        // Malformed user JSON -- fall through
      }
    }

    // 2. Auto-discover from primary workspace filesystem
    const discovered = discoverAgents(workspacePath)

    // 2b. Merge agents from other workspaces known to the CLI
    if (discovered && openclawBin) {
      const cliAgents = listCliAgents(openclawBin)
      if (cliAgents && cliAgents.length > 1) {
        return mergeExtraWorkspaces(discovered, cliAgents, workspacePath)
      }
      return discovered
    }
    if (discovered) return discovered

    // 3. CLI-only: no primary workspace agents, scan each CLI agent's workspace
    if (openclawBin) {
      const cliAgents = listCliAgents(openclawBin)
      if (cliAgents) {
        return mergeExtraWorkspaces([], cliAgents, '')
      }
    }
  }

  // 4. Bundled fallback
  return bundledRegistry as AgentEntry[]
}
