interaction:
  - name: "DeepInnovator"
    class_name: "recipe.DeepInnovator.DeepInnovator_interation.DeepInnovatorInteraction"
    config: {
      "enable_log": False,
      "num_retries": 10,
      "max_tokens": 2048,
      "temperature": 1.0,
      "discriminator_kwargs": {
        "discriminator_model": "your model",
        "api_key": "your api key",
        "api_base": "your api base",
        "max_tokens": 2048,
        "temperature": 1.0,
      }
    }